---
title: "CoAgMet"
author: "Miles Rollison"
date: "2/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=F)

#library(reticulate)
#Sys.setenv(RETICULATE_PYTHON =  ".venv/bin/python")

library(tidyverse)
library(magrittr)

directory = function(x){
    paste0(fakepath, x)
}
```

```{r}
lag_doubles = function(df, l = 1){
    output = df
    for(i in seq(1:l)){
        lags = df %>% 
            transmute_if(is.double, function(x){lag(x, i)}) %>%
            #rename_at(vars(everything(), -id), function(x){ paste0(x, "_lag", i) }) %>%
            mutate(id = id + i)
        output %<>% left_join(lags, by = "id", suffix = c("", paste0("_lag", i))) %>% select(id, everything())   
    }
    return(output)
}

rowMin = function(x){
    m = c()
    for (i in 1:nrow(x)) {
       m = c(m, min(x[i,]))
    }
    return(m)
}

rowMax = function(x){
    m = c()
    for (i in 1:nrow(x)) {
       m = c(m, max(x[i,]))
    }
    return(m)
}
```

```{r message=F}
cam_folder = directory("thesis/Data/CoAgMet/stations/")
regions = list.files(cam_folder)
start_index = 5


for (folder in regions) {
    files = list.files(paste0(cam_folder, folder))
    stations = gsub(".csv", '', files)
    previous = 0
    for (csv in files) {
        df = read_csv(paste0(cam_folder, folder, '/', csv)) %>%
            select(station, date, precip) %>% 
            filter(station != "variableTypes")
        varname = paste0("precip_", gsub(".csv", '', csv))
        colnames(df)[3] = varname
        
        df %<>% mutate(year = lubridate::year(date) %>% as.integer,
                      month = lubridate::month(date) %>% as.integer,
                      week = as.numeric(as.Date(date)+6 -
              as.Date(paste0((year - 1), "-12-31") )) %/% 7,
              week = ifelse(week == 53, 52, week) %>% as.integer) %>% 
            select( -station)
        
        df_monthly = df %>% 
            select(-week) %>% 
            group_by(year, month) %>% 
            summarise_if(is.double, function(x) sum(x, na.rm = T)) %>% 
            ungroup() %>% 
            arrange(year, month)
        df_weekly = df %>%
            select(-month) %>% 
            group_by(year, week) %>% 
            summarise_if(is.double, function(x) sum(x, na.rm = T)) %>% 
            ungroup() %>%
            arrange(year, week)
        
        
        if(!previous) {
            assign("region_df_monthly" , df_monthly, .GlobalEnv)
            assign("region_df_weekly" , df_weekly, .GlobalEnv)
            previous = 1
        }
        else{
            region_df_monthly %<>%
                full_join(df_monthly, by = c("year", "month")) 
            region_df_weekly %<>%
                full_join(df_weekly, by = c("year", "week"))
        }
       
    }
    
    region_df_monthly %<>% mutate(location = eval(folder),
                          id = 1:nrow(region_df_monthly) %>% as.double) %>%
        group_by(id, year, month, location) %>%
        summarise_if(is.double, function(x){sum(x, na.rm = T) }) %>% 
        ungroup()
    
    end_index = ncol(region_df_monthly)
    region_df_monthly$precip_avg = region_df_monthly[start_index:end_index] %>% rowMeans( na.rm = T)
    region_df_monthly$precip_min = region_df_monthly[start_index:end_index] %>% rowMin()
    region_df_monthly$precip_max = region_df_monthly[start_index:end_index] %>% rowMax()
    
    region_df_monthly %<>% select(id, year, month, location,
                          precip_avg, precip_min, precip_max) %>% 
        arrange(year, month)
    
    region_df_monthly %<>% lag_doubles(4)
    
    assign(eval(folder), region_df_monthly, .GlobalEnv)
    
     region_df_weekly %<>% mutate(location = eval(folder),
                          id = 1:nrow(region_df_weekly) %>% as.double) %>%
        group_by(id, year, week, location) %>% 
        summarise_if(is.double, function(x){sum(x, na.rm = T) }) %>% 
        ungroup()

    end_index = ncol(region_df_weekly)
    region_df_weekly$precip_avg = region_df_weekly[start_index:end_index] %>% rowMeans( na.rm = T)
    region_df_weekly$precip_min = region_df_weekly[start_index:end_index] %>% rowMin()
    region_df_weekly$precip_max = region_df_weekly[start_index:end_index] %>% rowMax()
    
    region_df_weekly %<>% select(id, year, week, location,
                          precip_avg, precip_min, precip_max) %>% 
        arrange(year, week)
    
    region_df_weekly %<>% lag_doubles(8)
    
    assign(paste0(eval(folder), '_weekly'), region_df_weekly, .GlobalEnv)
}

rm(cam_folder, csv, end_index, files, folder, previous, regions, start_index, stations, varname)
```

```{r}
coagmet = bind_rows(EC, NE, NWMA, SE, SLV, SW) %>%  
    arrange(year, month, location)

write_csv(coagmet, directory("thesis/Data/Constructed Datasets/coagmet_monthly.csv"))

coagmet_weekly = bind_rows(EC_weekly, NE_weekly, NWMA_weekly, SE_weekly,  SLV_weekly, SW_weekly) %>%  
    arrange(year, week, location)

write_csv(coagmet_weekly, directory("thesis/Data/Constructed Datasets/coagmet_weekly.csv"))
```

```{r}
rm(df, df_monthly, df_weekly, region_df_monthly, region_df_weekly, EC, NE, NWMA, SE, SLV, SW, EC_weekly, NE_weekly, NWMA_weekly, SE_weekly,  SLV_weekly, SW_weekly, coagmet, coagmet_weekly)
```

```{r}

```
