---
title: "Join all datasets"
author: "Miles Rollison"
date: "2/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=F)

#library(reticulate)
#Sys.setenv(RETICULATE_PYTHON =  ".venv/bin/python")

library(tidyverse)
library(magrittr)

directory = function(x){
    paste0(fakepath, x)
}
```

```{r}
col_types = paste0("iicccccddddc", paste0(rep("d", 35), collapse = ''))
hay = read_csv(directory("/thesis/Data/Constructed Datasets/hay_co_monthly_dm.csv"), col_types = col_types) %>% 
    filter(quality != "ALFALFA_NA")

col_types = paste0("iiccccddc", paste0(rep("d", 38), collapse = ''))
corn = read_csv(directory("/thesis/Data/Constructed Datasets/corn_co_monthly_dm.csv"), col_types = col_types)

col_types = paste0("iici", paste0(rep("d", 48), collapse = ''))
spei = read_csv(directory("/thesis/Data/Constructed Datasets/spei.csv"), col_types = col_types)

col_types = paste0("iic", paste0(rep("d", 39), collapse = ''))
coagmet = read_csv(directory("/thesis/Data/Constructed Datasets/coagmet.csv"), col_types = col_types)

rm(col_types)
```

```{r}
rename_locations = function(x){
    x %<>% mutate(location = case_when(
        location == "EC" ~ "East Central Colorado",
        location == "NE" ~ "Northeast Colorado",
        location == "NWMA" ~ "Mountains and Northwest",
        location == "SE" ~ "Southeast Colorado",
        location == "SLV" ~ "San Luis Valley",
        location == "SW" ~ "South Western Colorado",
        TRUE ~ "ERROR"))
    return(x)
}

spei = rename_locations(spei)
coagmet = rename_locations(coagmet)

spei %<>% select(year, month, location, TimeStep, 
                SPEI_avg, SPEI_min, SPEI_max, 
                SPEI_avg_lag1, SPEI_min_lag1, SPEI_max_lag1)
```

Test out different SPEI Timesteps

```{r}
hay %<>% mutate(price_inc = ifelse(price_diff > 0, 1, 0) %>% as_factor()) %>% filter(!is.na(price_inc))
df3 = hay %>% right_join(spei %>% filter(TimeStep == 3) ) %>% filter( !is.na(bid_avg))
df4 = hay %>% right_join(spei %>% filter(TimeStep == 4) ) %>% filter( !is.na(bid_avg))
df5 = hay %>% right_join(spei %>% filter(TimeStep == 5) ) %>% filter( !is.na(bid_avg))
df6 = hay %>% right_join(spei %>% filter(TimeStep == 6) ) %>% filter( !is.na(bid_avg))
```

Stepwise probit to compare predictive accuracy

```{r}
indexes = sample(1:nrow(df3), nrow(df3)/3) # All df have same rows
dfs = c("df3", "df4", "df5", "df6")
for (i in dfs) {
    df = eval(as.name(i))
    df %<>% select(-bid_high, -bid_low, -bid_avg, -spread,
                   -price_diff, -price_lag, -diff_pct)
                   
    #assign(paste0("testing", i), df[indexes,], .GlobalEnv)
    training = df[-indexes,]

    stp = step(glm(price_inc ~ D0_lag1 + D1_lag1 + D2_lag1 + D3_lag1 + D4_lag1 + D2plus_lag1
               + D0_lag2 + D1_lag2 + D2_lag2 + D3_lag2 + D4_lag2 + D2plus_lag2 
               + D0_lag3 + D1_lag3 + D2_lag3 + D3_lag3 + D4_lag3 + D2plus_lag3 
               + D0_lag4 + D1_lag4 + D2_lag4 + D3_lag4 + D4_lag4 + D2plus_lag4 
               + D0 + D1 + D2 + D3 + D4 + D2plus 
               + SPEI_avg + SPEI_min + SPEI_max 
               + SPEI_avg_lag1 + SPEI_min_lag1 + SPEI_max_lag1,
               family = binomial(link = "probit"), data = training,
               na.action = na.omit), trace = 0)
    assign(paste0(i, "_probit"), stp, .GlobalEnv)
    
    pr = predict(stp, testing, type = "response")
    predictions = data.frame(predicted = round(pr) %>% as_factor(),
                             observed = testing$price_inc %>% as_factor()) %>%
        na.omit()
    
    cm = confusionMatrix(data = predictions$predicted,
                         reference = predictions$observed)
    
    assign(paste0(i, "_cm"), cm, .GlobalEnv)
    print(paste(i, "complete"))
}
```

```{r}
df3_cm
df4_cm
df5_cm
df6_cm
```
