---
title: "Monthly Dataset Construction Code Cleanup"
author: "Miles Rollison"
date: "2/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=F)

#library(reticulate)
#Sys.setenv(RETICULATE_PYTHON =  ".venv/bin/python")

library(tidyverse)
library(magrittr)
```

```{r functions}
make_lags = function(df, v, l= 1){
    for(i in seq(1:l)){
        df %<>% 
            mutate_at(v, function(x){lag(x, i)}) %>%
            rename_at(v, function(x){ paste0(x, "_lag", i) }) %>%
            full_join(df)   
    }
    return(df)
}
```

```{r hay}
hay = read_csv(paste0(fakepath, "thesis/Data/AMS/OriginalReports/hay_reports_stacked.csv"))

hay %<>% separate(location, into = c("location", "state"), sep = ', ') %>% 
    filter(state == "CO") %>% 
    mutate(year = lubridate::year(month),
           month = lubridate::month(month),
           bid_avg = (bid_low + bid_high) / 2,
           spread = bid_high - bid_low,
           units = units %>% tolower %>% gsub(" bales", '', .),
           quality = paste(class, `grade description`, sep = '_'),
           location = case_when(
               location == "Mountain Area" ~ "Mountains and Northwest",
               location == "Western Slope Area" ~ "Mountains and Northwest",
               TRUE ~ location)) %>% 
    rename(grade = `grade description`) %>% 
    select(year, month, everything(), -variety, -transmode, -`pricing point`, -`delivery period`) %>% 
    arrange(location, year, month) %>% 
    filter(quality != "ALFALFA_NA")

hay %<>% group_by(location, quality) %>%
    mutate(price_lag = lag(bid_avg),
           price_diff = bid_avg - price_lag,
           diff_pct = round(price_diff / bid_avg, 4),
           price_inc = sign(diff_pct))
```

```{r corn}
corn = read_csv(paste0(fakepath, "thesis/Data/AMS/OriginalReports/corn_reports_stacked.csv"))

corn %<>% separate(location, into = c("location", "state"), sep = ', ') %>% 
    filter(state == "CO") %>% 
    mutate(year = lubridate::year(month),
           month = lubridate::month(month),
           bid_avg = (bid_low + bid_high) / 2,
           price_cwt = case_when(
               units == "Bushel" ~ (bid_avg / 54) * 100,
               TRUE ~ bid_avg),
           spread = bid_high - bid_low) %>% 
    select(year, month, everything(), -variety, -`grade description`, -`delivery period`, -class) %>% 
    filter(location != "Southwest Nebraska / Southeast Wyoming")

corn %<>% group_by(location) %>%
    mutate(price_lag = lag(bid_avg),
           price_diff = round(bid_avg - price_lag, 4),
           diff_pct = round(price_diff / bid_avg, 4),
           price_inc = sign(diff_pct))

```

```{r drought}
dm = read_csv(paste0(fakepath, "thesis/Data/Drought Monitor/totalArea_categorical_byCounty_CO_20000101_20191219.csv"))   

counties = read_csv(paste0(fakepath, "thesis/Data/counties_in_regions_CO_FIPS.csv"))

#Aggregate to month level
dm %<>% group_by(year, month, County) %>%
    summarise_if(is.numeric, mean)

#Join with region classifications
dm %<>% ungroup %>% mutate(County = str_replace(County, " County", ''),
               year = as.integer(year),
               month = as.integer(month),
               D2plus = D2 + D3 + D4) %>% 
    full_join(counties) %>% 
    mutate_if(is.double, function(x) x / 1000)

dmh = dm %>% group_by(year, month, ams_hay_region) %>% 
    summarise_if(is.numeric, sum) %>% 
    select(-FIPS) %>% 
    arrange(year, month)

dmc = dm %>% group_by(year, month, ams_corn_region)  %>% 
    summarise_if(is.numeric, sum) %>% 
    select(-FIPS) %>% 
    arrange(year, month) 

dmh %<>% group_by(ams_hay_region) %>% make_lags( vars(D0, D1, D2, D3, D4, D2plus), 4)
dmc %<>% group_by(ams_corn_region) %>% make_lags( vars(D0, D1, D2, D3, D4, D2plus), 4)
```

```{r join}
hay %<>% full_join(dmh, by = c("location" = "ams_hay_region", "year", "month"))
corn %<>% full_join(dmc, by = c("location" = "ams_corn_region", "year", "month")) %>% arrange(year, month, location)

rm(dm, dmc, dmh, counties)
```

```{r write}
write_csv(hay, paste0(fakepath, "thesis/Data/Constructed Datasets/hay_co_monthly_dm.csv"))
write_csv(corn, paste0(fakepath, "thesis/Data/Constructed Datasets/corn_co_monthly_dm.csv"))

rm(hay, corn)
```
