---
title: "SPEI"
author: "Miles Rollison"
date: "2/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=F)

#library(reticulate)
#Sys.setenv(RETICULATE_PYTHON =  ".venv/bin/python")

library(tidyverse)
library(magrittr)

directory = function(x){
    paste0(fakepath, x)
}
```

```{r functions}
lag_doubles = function(df, l = 1){
    output = df
    for(i in seq(1:l)){
        lags = df %>% 
            transmute_if(is.double, function(x){lag(x, i)}) %>%
            #rename_at(vars(everything(), -id), function(x){ paste0(x, "_lag", i) }) %>%
            mutate(id = id + i)
        output %<>% left_join(lags, by = "id", suffix = c("", paste0("_lag", i))) %>% select(id, everything())   
    }
    return(output)
}
```

```{r}
rowMin = function(x){
    m = c()
    for (i in 1:nrow(x)) {
       m = c(m, min(x[i,]))
    }
    return(m)
}

rowMax = function(x){
    m = c()
    for (i in 1:nrow(x)) {
       m = c(m, max(x[i,]))
    }
    return(m)
}
```

```{r}
da_folder = directory("thesis/Data/Drought Risk Atlas/")
regions = list.files(da_folder)
start_index = 4
for (folder in regions) {
    files = list.files(paste0(da_folder, folder))
    stations = gsub("dra_export_\\d+|.csv", '', files)
    previous = 0
    for (csv in files) {
        df = read_csv(paste0(da_folder, folder, '/', csv), col_types = "cdli") %>%
            mutate(Date = gsub(" 12:00:00 AM", '', Date)) %>%
            separate(Date, into = c("month", "day", "year"), sep = '/') %>%
            mutate(year = year %>% as.integer,
                   month = month %>% as.integer) %>% 
            select(year, month, TimeStep, SPEI, -day, -HasNoData)

        varname = paste0("SPEI_", gsub("dra_export_\\d+|.csv", '', csv))
        colnames(df)[start_index] = varname
        if(!previous){
            assign("region_df" , df, .GlobalEnv)
            previous = 1
        }
        else region_df %<>% full_join(df, by = c("year", "month", "TimeStep"))
    }
    end_index = ncol(region_df)
    region_df %<>% mutate(id = 1:nrow(region_df) %>% as.double,
                          SPEI_avg = rowMeans(region_df[start_index:end_index], na.rm = T),
                          SPEI_min = rowMin(region_df[start_index:end_index]),
                          SPEI_max = rowMax(region_df[start_index:end_index]),
                          location = eval(folder),
                          TimeStep = TimeStep %>% as.integer) %>% 
        select(year, month, location, everything()) %>% 
        arrange(TimeStep, year, month)
    
    region_df %<>% select(id, year, month, location, TimeStep, SPEI_avg, SPEI_min, SPEI_max) 
    
    region_df %<>% group_by(TimeStep) %>%
        lag_doubles(4) %>%
        select(-contains("TimeStep_lag")) 
    
    assign(eval(folder), region_df, .GlobalEnv)
    #cor(region_df[start_index:index]) %>% print
}

rm(csv, da_folder, end_index, files, folder, previous, regions, start_index, stations, varname)
```

```{r}
spei = bind_rows(EC, NE, NWMA, SE, SLV, SW)
spei %<>% arrange(location,  TimeStep, year, month)

write_csv(spei, directory("thesis/Data/Constructed Datasets/spei.csv"))
```

```{r}

```